name: Build and Create Release

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  generate:
    name: Generate Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM gcc Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Verify ARM gcc Version
        run: arm-none-eabi-gcc --version
        
      - name: Make Release
        run: make release

      # - name: List build directory contents
      #   run: ls -al

      # - name: Compress build artifacts
      #   run: zip -r output_build.zip ./build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4 
        with:
          name: build 
          path: ./release

  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    needs: generate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_tag_name
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
      - name: Download Build Artifact
        uses: actions/download-artifact@v4 
        with:
          name: build
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{ env.tag_name }}
          files: ./release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          